// const a = 3.7;
// const flooraValue = Math.floor(a);
// const ceilaValue = Math.ceil(a);
// const roundaValue = Math.round(a);
// const truncaValue = Math.trunc(a);
// console.log(`main value-${a}`);

// console.log(`Floor-${flooraValue}`);
// console.log(`ceil-${ceilaValue}`);
// console.log(`Round-${roundaValue}`);
// console.log(`Trunc-${truncaValue}`);
// const b = -3.7;
// console.log(`main value-${b}`);
// const floorbValue = Math.floor(b);
// const ceilbValue = Math.ceil(b);
// const roundbValue = Math.round(b);
// const truncbValue = Math.trunc(b);
// console.log(`Floor-${floorbValue}`);
// console.log(`ceil-${ceilbValue}`);
// console.log(`Round-${roundbValue}`);
// console.log(`Trunc-${truncbValue}`);
console.log(Math.random());
console.log(Math.random() * 100);
const myRandomValue = Math.random() * 100;
console.log(`My value=${myRandomValue}`);
console.log(Math.round(myRandomValue));
console.log(Math.floor(myRandomValue));
console.log(Math.ceil(myRandomValue));
console.log(Math.trunc(myRandomValue));
console.log(myRandomValue.toFixed(3));
console.log(myRandomValue.toPrecision(4));
